// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 8.3.11
// Project name: Pantalla_psicrometro

#include "ui.h"

lv_obj_t * ui_Screen2 = NULL;
lv_obj_t * ui_Label1 = NULL;
lv_obj_t * ui_Label2 = NULL;
lv_obj_t * ui_Label3 = NULL;
lv_obj_t * ui_Label4 = NULL;
lv_obj_t * ui_uiLabelTbs = NULL;
lv_obj_t * ui_uiLabelTbh = NULL;
lv_obj_t * ui_uiLabelRef = NULL;
lv_obj_t * ui_uiLabelHum = NULL;
lv_obj_t * ui_GrafHum = NULL;
lv_obj_t * ui_uiLabelFecha = NULL;
lv_obj_t * ui_uiLabelHora = NULL;
// event funtions

// build funtions

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 2
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 2
    lv_obj_set_x(ui_Label1, -83);
    lv_obj_set_y(ui_Label1, -84);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "Tbs");

    ui_Label2 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, -81);
    lv_obj_set_y(ui_Label2, -58);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "Tbh");

    ui_Label3 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, -79);
    lv_obj_set_y(ui_Label3, -33);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "Tbs reference");

    ui_Label4 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, 0);
    lv_obj_set_y(ui_Label4, -4);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "Humidity");

    ui_uiLabelTbs = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_uiLabelTbs, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_uiLabelTbs, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_uiLabelTbs, 63);
    lv_obj_set_y(ui_uiLabelTbs, -81);
    lv_obj_set_align(ui_uiLabelTbs, LV_ALIGN_CENTER);
    lv_label_set_text(ui_uiLabelTbs, "00.0 °C");

    ui_uiLabelTbh = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_uiLabelTbh, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_uiLabelTbh, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_uiLabelTbh, 63);
    lv_obj_set_y(ui_uiLabelTbh, -57);
    lv_obj_set_align(ui_uiLabelTbh, LV_ALIGN_CENTER);
    lv_label_set_text(ui_uiLabelTbh, "00.0 °C");

    ui_uiLabelRef = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_uiLabelRef, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_uiLabelRef, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_uiLabelRef, 63);
    lv_obj_set_y(ui_uiLabelRef, -34);
    lv_obj_set_align(ui_uiLabelRef, LV_ALIGN_CENTER);
    lv_label_set_text(ui_uiLabelRef, "00.0 °C");

    ui_uiLabelHum = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_uiLabelHum, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_uiLabelHum, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_uiLabelHum, 3);
    lv_obj_set_y(ui_uiLabelHum, 68);
    lv_obj_set_align(ui_uiLabelHum, LV_ALIGN_CENTER);
    lv_label_set_text(ui_uiLabelHum, "00%");

    ui_GrafHum = lv_arc_create(ui_Screen2);
    lv_obj_set_width(ui_GrafHum, 152);
    lv_obj_set_height(ui_GrafHum, 108);
    lv_obj_set_x(ui_GrafHum, 23);
    lv_obj_set_y(ui_GrafHum, 72);
    lv_obj_set_align(ui_GrafHum, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_GrafHum, 50);

    ui_uiLabelFecha = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_uiLabelFecha, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_uiLabelFecha, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_uiLabelFecha, -40);
    lv_obj_set_y(ui_uiLabelFecha, -106);
    lv_obj_set_align(ui_uiLabelFecha, LV_ALIGN_CENTER);
    lv_label_set_text(ui_uiLabelFecha, "2026/09/12");

    ui_uiLabelHora = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_uiLabelHora, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_uiLabelHora, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_uiLabelHora, 51);
    lv_obj_set_y(ui_uiLabelHora, -106);
    lv_obj_set_align(ui_uiLabelHora, LV_ALIGN_CENTER);
    lv_label_set_text(ui_uiLabelHora, "18:16 hrs");

}

void ui_Screen2_screen_destroy(void)
{
    if(ui_Screen2) lv_obj_del(ui_Screen2);

    // NULL screen variables
    ui_Screen2 = NULL;
    ui_Label1 = NULL;
    ui_Label2 = NULL;
    ui_Label3 = NULL;
    ui_Label4 = NULL;
    ui_uiLabelTbs = NULL;
    ui_uiLabelTbh = NULL;
    ui_uiLabelRef = NULL;
    ui_uiLabelHum = NULL;
    ui_GrafHum = NULL;
    ui_uiLabelFecha = NULL;
    ui_uiLabelHora = NULL;

}
