// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 8.3.11
// Project name: Pantalla_psicrometro

#include "ui.h"

lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_Label9 = NULL;
lv_obj_t * ui_Label10 = NULL;
lv_obj_t * ui_ImgBoton = NULL;
// event funtions
void ui_event_ImgBoton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen2_screen_init);
    }
}

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label9 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label9, 0);
    lv_obj_set_y(ui_Label9, -100);
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label9, "PSICROMETRO DIGITAL");

    ui_Label10 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label10, -8);
    lv_obj_set_y(ui_Label10, -77);
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "M&T TEAM");

    ui_ImgBoton = lv_imgbtn_create(ui_Screen1);
    lv_imgbtn_set_src(ui_ImgBoton, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_1555184149, NULL);
    lv_obj_set_width(ui_ImgBoton, 266);
    lv_obj_set_height(ui_ImgBoton, 159);
    lv_obj_set_x(ui_ImgBoton, 0);
    lv_obj_set_y(ui_ImgBoton, 30);
    lv_obj_set_align(ui_ImgBoton, LV_ALIGN_CENTER);

    lv_obj_add_event_cb(ui_ImgBoton, ui_event_ImgBoton, LV_EVENT_ALL, NULL);

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_Label9 = NULL;
    ui_Label10 = NULL;
    ui_ImgBoton = NULL;

}
