// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 8.3.11
// Project name: Pantalla_psicrometro

#ifndef UI_SCREEN2_H
#define UI_SCREEN2_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen2
extern void ui_Screen2_screen_init(void);
extern void ui_Screen2_screen_destroy(void);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_uiLabelTbs;
extern lv_obj_t * ui_uiLabelTbh;
extern lv_obj_t * ui_uiLabelRef;
extern lv_obj_t * ui_uiLabelHum;
extern lv_obj_t * ui_GrafHum;
extern lv_obj_t * ui_uiLabelFecha;
extern lv_obj_t * ui_uiLabelHora;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

